ALTER TABLE booking
DROP
FOREIGN KEY FK_BOOKING_ON_DRIVERREVIEW;

ALTER TABLE review
    ADD booking_id BIGINT NULL;

ALTER TABLE review
    ADD CONSTRAINT FK_REVIEW_ON_BOOKING FOREIGN KEY (booking_id) REFERENCES booking (id);

ALTER TABLE booking
DROP
COLUMN driver_review_id;
